name: Learning
title: HOME

tagline: Change `tagline` in `_config.yml`

menu:
  - title:             Example
    url:               /example/
  - title:             Documentation
    url:               /docs/
  - title:             About
    url:               /about/



