name: Learning
title: HOME

menu:
  - title:             Example
    url:               /example/
  - title:             Documentation
    url:               /docs/
  - title:             About
    url:               /about/



